V        REM  +----------------------------------------------+
X        REM  | QUICK_HACK.BAS (targeted checkpass runner)   |
XV       REM  +----------------------------------------------+
XX       REM
XXV      IF ARGS() > I THEN GOTO LXXXV
XXX      PRINT "usage: ./quick_hack.exe username"
XXXV     PRINT CHR(X)
XL       END
LXXXV    REM
XC       DIM username AS STRING
XCV      username = ARG(II)
C        DIM pwdcount AS INTEGER
CV       pwdcount = CXX
CX       DIM words(pwdcount) AS STRING
CXV      words(I) = "ftd"
CXX      words(II) = "flower"
CXXV     words(III) = "flowers"
CXXX     words(IV) = "florist"
CXXXV    words(V) = "florists"
CXL      words(VI) = "bouquet"
CXLV     words(VII) = "roses"
CL       words(VIII) = "delivery"
CLV      words(IX) = "telegraph"
CLX      words(X) = "teleflora"
CLXV     words(XI) = "flora"
CLXX     words(XII) = "knr"
CLXXV    words(XIII) = "kernighan"
CLXXX    words(XIV) = "ritchie"
CLXXXV   words(XV) = "kandr"
CXC      words(XVI) = "kr"
CXCV     words(XVII) = "c"
CC       words(XVIII) = "cprogramming"
CCV      words(XIX) = "thecprogramminglanguage"
CCX      words(XX) = "unix"
CCXV     words(XXI) = "bell"
CCXX     words(XXII) = "plan9"
CCXXV    words(XXIII) = "bbarker"
CCXXX    words(XXIV) = "barker"
CCXXXV   words(XXV) = "bob"
CCXL     words(XXVI) = "bobby"
CCXLV    words(XXVII) = "price"
CCL      words(XXVIII) = "priceisright"
CCLV     words(XXIX) = "thepriceisright"
CCLX     words(XXX) = "comeondown"
CCLXV    words(XXXI) = "spay"
CCLXX    words(XXXII) = "spayneuter"
CCLXXV   words(XXXIII) = "spayandneuter"
CCLXXX   words(XXXIV) = "plinko"
CCLXXXV  words(XXXV) = "bigwheel"
CCXC     words(XXXVI) = "showcase"
CCXCV    words(XXXVII) = "showdown"
CCC      words(XXXVIII) = "carey"
CCCV     words(XXXIX) = "drew"
CCCX     words(XL) = "comeon"
CCCXV    words(XLI) = "neuter"
CCCXX    words(XLII) = "down"
CCCXXV   words(XLIII) = "transworld"
CCCXXX   words(XLIV) = "transworlddelivery"
CCCXXXV  words(XLV) = "floristsdelivery"
CCCXL    words(XLVI) = "floriststransworld"
CCCXLV   words(XLVII) = "floriststransworlddelivery"
CCCL     words(XLVIII) = "floral"
CCCLV    words(XLIX) = "ftdflorist"
CCCLX    words(L) = "ftdflorists"
CCCLXV   words(LI) = "ftdflowers"
CCCLXX   words(LII) = "ftdfloral"
CCCLXXV  words(LIII) = "bouquets"
CCCLXXX  words(LIV) = "rose"
CCCLXXXV words(LV) = "orchid"
CCCXC    words(LVI) = "orchids"
CCCXCV   words(LVII) = "tulip"
CD       words(LVIII) = "tulips"
CDV      words(LIX) = "daisy"
CDX      words(LX) = "daisies"
CDXV     words(LXI) = "lily"
CDXX     words(LXII) = "lilies"
CDXXV    words(LXIII) = "carnation"
CDXXX    words(LXIV) = "carnations"
CDXXXV   words(LXV) = "valentine"
CDXL     words(LXVI) = "valentines"
CDXLV    words(LXVII) = "mothersday"
CDL      words(LXVIII) = "birthday"
CDLV     words(LXIX) = "anniversary"
CDLX     words(LXX) = "kernighanritchie"
CDLXV    words(LXXI) = "brian"
CDLXX    words(LXXII) = "dennis"
CDLXXV   words(LXXIII) = "bwk"
CDLXXX   words(LXXIV) = "dmr"
CDLXXXV  words(LXXV) = "cprog"
CDXC     words(LXXVI) = "cprogram"
CDXCV    words(LXXVII) = "cprogramminglanguage"
CDXCIX   words(LXXVIII) = "thecprogramming"
D        words(LXXIX) = "unixprogramming"
DV       words(LXXX) = "ansi"
DX       words(LXXXI) = "c89"
DXV      words(LXXXII) = "c90"
DXX      words(LXXXIII) = "c99"
DXXV     words(LXXXIV) = "c11"
DXXX     words(LXXXV) = "kandrtwo"
DXXXV    words(LXXXVI) = "kandrs"
DXL      words(LXXXVII) = "kandr2"
DXLV     words(LXXXVIII) = "kandr3"
DXLVI    words(LXXXIX) = "flowersbytelegraph"
DXLVII   words(XC) = "flowerstoday"
DXLVIII  words(XCI) = "flowersby"
DXLIX    words(XCII) = "flowersdelivery"
DL       words(XCIII) = "flowerdelivery"
DLI      words(XCIV) = "floristdelivery"
DLII     words(XCV) = "ftdinc"
DLIII    words(XCVI) = "ftdincorporated"
DLIV     words(XCVII) = "ftdfloristsdelivery"
DLV      words(XCVIII) = "ftdflowersdelivery"
DLVI     words(XCIX) = "ftdfloraldelivery"
DLVII    words(C) = "transworldflorists"
DLVIII   words(CI) = "transworldfloristsdelivery"
DLIX     words(CII) = "floristtransworlddelivery"
DLX      words(CIII) = "floristtransworld"
DLXI     words(CIV) = "floristsbytelegraph"
DLXII    words(CV) = "kernighanandritchie"
DLXIII   words(CVI) = "ritchieandkernighan"
DLXIV    words(CVII) = "briankernighan"
DLXV     words(CVIII) = "dennisritchie"
DLXVI    words(CIX) = "ken"
DLXVII   words(CX) = "thompson"
DLXVIII  words(CXI) = "kenanddennis"
DLXIX    words(CXII) = "kenandritchie"
DLXX     words(CXIII) = "kenandbrian"
DLXXI    words(CXIV) = "kr2"
DLXXII   words(CXV) = "kr2e"
DLXXIII  words(CXVI) = "knr2e"
DLXXIV   words(CXVII) = "kandr2e"
DLXXV    words(CXVIII) = "cprogramminglanguage2e"
DLXXVI   words(CXIX) = "thecprogramminglanguage2e"
DLXXVII  words(CXX) = "belllabs"
DC       PRINT "attempting quick list of " + pwdcount + " passwords " + CHR(X)
DCV      DIM i AS INTEGER
DCX      i = I
DCXV     IF CHECKPASS(username, words(i)) THEN GOTO DCXL
DCXX     i = i + I
DCXXV    IF i > pwdcount THEN GOTO DCLV
DCXXX    GOTO DCXV
DCXL     PRINT "found match!! for user " + username + CHR(X)
DCXLV    PRINT "password: " + words(i) + CHR(X)
DCL      END
DCLV     PRINT "no quick matches for user " + username + CHR(X)
DCLX     END
